### ISSUE TITLE
error when invoking as a standalone module

### ISSUE THREAD

**Issue by hville** [pinguxx/sm-table#1]
The decision to have `table.view = function (data) {...}` instead of `table.view = function (ctrl) {...}` leads to unexpected results because it is breaking the mithril convention:

This works as in the example because no parameter is passed to table.view

``` javascript
var table = new Table({ columns: ['id', 'val'], data: data });
  m.module(window.document.body,  {
  controller: function () {},
  view: function() {return table.view()}
});
```

But this fails:

``` javascript
var table = new Table({ columns: ['id', 'val'], data: data });
  m.module(window.document.body,  {
  controller: function () {},
  view: table.view
});  //  Uncaught Error: table needs an array of data
```

And this also fails:

``` javascript
var table = new Table({ columns: ['id', 'val'], data: data });
m.module(window.document.body, table);  
//  Uncaught Error: table needs an array of data
```

To keep with the mithril convention, I would suggest that passing of new data can only be used with `table.setData(data)` to change `table.vm.data` and that `table.view(ctrl)` renders directly from `table.vm.data`.

Because of this, I was certain this component was broken until I tried the provided example. Took me a while to find out why I was always getting the error.

**Comment by pinguxx** [comment]
yeah, i didn't catch that, i will push a fix in a moment
for the moment i will leave the parameter open but i may take it away later since it break the conventions
thanks for the bug
